[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "java -jar -Dspring.profiles.active=prod app.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"