server:
  port: ${PORT:8767}

spring:
  application:
    name: discovery-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

eureka:
  instance:
    hostname: ${RAILWAY_PUBLIC_DOMAIN:discover-service-production.up.railway.app}
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.netflix.discovery: INFO
    com.netflix.eureka: INFO
    org.springframework.cloud.netflix.eureka: INFO