server:
  port: 8767

spring:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: ec2-16-171-41-109.eu-north-1.compute.amazonaws.com
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
