server:
  port: ${PORT:8767}  # Railway dynamic port; fallback to 8767 locally

spring:
  application:
    name: discovery-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

eureka:
  instance:
    hostname: ${RAILWAY_PUBLIC_DOMAIN:localhost}  # Railway public domain
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: false
    renewal-percent-threshold: 0.85
    response-cache-update-interval-ms: 5000
    response-cache-auto-expiration-in-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: false
  metrics:
    export:
      simple:
        enabled: false

logging:
  level:
    root: ERROR
    com.netflix.discovery: ERROR
    com.netflix.eureka: ERROR
    org.springframework.cloud.netflix.eureka: ERROR
  pattern:
    console: "%msg%n"
